name: Library Management CI

on:
  push:
    branches:
      - main

jobs:
  validate-project:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Show Project Files
        run: ls -R

      - name: Check README File
        run: test -f README.md

      - name: Check CI Pipeline Folder
        run: test -d ci-pipeline

      - name: Check Pipeline Description File
        run: test -f ci-pipeline/pipeline_description.md

      - name: Check Validation Process File
        run: test -f ci-pipeline/validation_process.txt

      - name: Check Workflow Explanation File
        run: test -f ci-pipeline/ci_workflow_explanation.txt

      - name: Success Message
        run: echo "All required files are present. CI Passed Successfully!"
